---
name: Check for new usages of deprecated functionality

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/gradually-deprecated.yaml'
      - './scripts/run-gradually-deprecated.sh'
      - '**.go'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./.go-version
      - run: bash ./scripts/run-gradually-deprecated.sh
      - name: Add waiting-response on fail
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["waiting-response"]
            })
