---
name: Validate Examples

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/validate-examples.yaml'
      - 'examples/**'

concurrency:
  group: 'examples-${{ github.head_ref }}'
  cancel-in-progress: true

jobs:
  website-lint:
    runs-on: [custom, linux, large]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./.go-version
      - run: bash scripts/gogetcookie.sh
      - run: make tools
      - run: make validate-examples
      - name: Add waiting-response on fail
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["waiting-response"]
            })
